### ISSUE TITLE
Join Configuration no Hibernate

### ISSUE THREAD

**Issue by thiagopaschoal** [thiagopaschoal/casadocodigo#1]
Tudo bem Alberto, 

Seguinte estou com dificuldade no relacionamento do Livro para com o Autor. Na classe Book eu adicionei um relacionamento do tipo OneToOne com Author poré toda vez que insiro um registro no banco e depois eu retorno usando um select, o valor do autor vem null. Quando isso acontece? Poderia me ajudar a entender este problema?

Obrigado

**Comment by asouza** [comment]
Oi Thiago,

Eu sempre começo pelo basico. Lá na tabela, a chave estrangeira tá ok? O
melhor era eu ter acesso a progressão do PR :).

Outra coisa, o mesmo autor pode escrever mais de um livro, então o melhor é
usar um ManyToOne.

Abraço!

Em dom, 24 de nov de 2019 15:14, Thiago Sakurai Paschoal <
notifications@github.com> escreveu:
